spring:
  application:
    name: tasks
  cloud:
    stream:
      bindings:
        output: tasks
        contentType: application/json
  data:
    mongodb:
      database: tasks

  # can be overridden with -Dspring.profiles.active or in IntelliJ run config
  profiles:
    active: local
