spring:
  cloud:
    stream:
      bindings:
        output:
          destination: tasks
          contentType: application/json
  data:
    mongodb:
      database: tasks

  # can be overridden with -Dspring.profiles.active or in IntelliJ run config
  profiles:
    active: local
