version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  consul:
    image: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1 # override for prod
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
